repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version (update periodically by running 'pre-commit autoupdate')
  rev: v0.15.0
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi, jupyter ]

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.9
  hooks:
    - id: actionlint
      name: Lint GitHub Actions workflows
      # For now, only run on the pixi workflows
      files: ^\.github/workflows/.*_pixi\.ya?ml$
      # files: ^\.github/workflows/.*\.ya?ml$
